name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      

    - name: Log in to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: flask
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          working-directory: app
          run: docker build . --file Dockerfile --tag devops-test-klaver:$(date +%s)


       
