name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    
    steps:
    - uses: actions/checkout@v3

      

    - name: Log in to Docker Hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: flaskproject/image-name
          tags: v1, latest
          registry: docker.io
          dockerfile: app/Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          


       
