name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - uses: workflow/nix-shell-action@v3
      with:
        interpreter: default is bash
        
        packages: default is bash
        
        script: cd /app 
        
        run: docker build . --file app/Dockerfile --tag my-image-name:$(date +%s)
